## Adding init script to add more databases for the different comonents
## See: https://hub.docker.com/_/postgres #Initialization scripts for more info
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init-user-db.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE canary_checker;
        CREATE DATABASE config_db;
        CREATE DATABASE incident_commander;
        GRANT ALL PRIVILEGES ON DATABASE canary_checker TO "$POSTGRES_USER";
        GRANT ALL PRIVILEGES ON DATABASE config_db TO "$POSTGRES_USER";
        GRANT ALL PRIVILEGES ON DATABASE incident_commander TO "$POSTGRES_USER";
    EOSQL