---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-db
  labels:
    control-plane: config-db
spec:
  selector:
    matchLabels:
      control-plane: config-db
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: config-db
    spec:
      serviceAccountName: config-db-sa
      containers:
        - name: config-db
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: config-db-postgres-connection-string
                  key: connection-string
---
apiVersion: v1
kind: Namespace
metadata:
  name: config-db
  labels:
    control-plane: config-db
$patch: delete