apiVersion: v1
data:
  connection-string: cG9zdGdyZXNxbDovL3Bvc3RncmVzOlNvbTNQYXNzd2RAcG9zdGdyZXMtZGIuaW5jaWRlbnQtY29tbWFuZGVyL2NvbmZpZ19kYg==
kind: Secret
metadata:
  name: config-db-postgres-connection-string