{{- if empty .Values.db.secretKeyRef.name }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-postgres-db
  labels:
    {{- include "incident-commander.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: create-postgres-db
          image: usql/postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretKeyRef.name | default "postgres-connection" }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretKeyRef.name | default "postgres-connection" }}
                  key: POSTGRES_PASSWORD
          command: ["bash"]
          args:
            - c
            - |
              echo postgres/postgres:$POSTGRES_USER:$POSTGRES_PASSWORD > ~/.pgpass
              psql -h postgres -u $POSTGRES_USER -c 'create database incident_commander'
              psql -h postgres -u $POSTGRES_USER -c 'create database config-db'
              psql -h postgres -u $POSTGRES_USER -c 'create database canary-checker'


      restartPolicy: Never
{{- end }}
