{{- if eq .Values.db.enabled true }}

---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: docker.io/supabase/postgres:14.1.0.21
        volumeMounts:
          - name: postgresql
            mountPath: /data
        envFrom:
          - secretRef:
              name: {{ .Values.db.secretKeyRef.name }}
  volumeClaimTemplates:
  - metadata:
      name: postgresql
    spec:
      accessModes: ["ReadWriteOnce"]
      {{ if .Values.db.storageClass }}
      storageClassName: {{ .Values.db.storageClass }}
      {{ end }}
      resources:
        requests:
          storage: {{ .Values.db.storage }}

---

# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432

---


{{- if .Values.db.secretKeyRef.create  }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretKeyRef.name }}
type: Opaque
stringData:
  {{- $secretObj := ( lookup "v1" "Secret" .Release.Namespace .Values.db.secretKeyRef.name ) }}
  {{- $secretData := ( get $secretObj "stringData" ) | default dict }}
  {{- $user :=  (( get $secretData "POSTGRES_USER" ) | b64dec ) | default "postgres"  }}
  {{ $password := "" }}
  {{- if .Release.IsInstall }}
  {{- $password =  (( get $secretData "POSTGRES_PASSWORD") | b64dec ) | default ( randAlphaNum 32 )  }}
  {{ else }}
  {{- $password = (index (lookup "v1" "Secret" .Release.Namespace .Values.db.secretKeyRef.name).data "POSTGRES_PASSWORD") | b64dec }}
  {{ end }}
  {{- $host := print "postgres." .Release.Namespace  ".svc.cluster.local:5432" }}
  {{- $url := print "postgresql://" $user ":" $password "@" $host }}

  {{- $configDbUrl := ( get $secretData .Values.db.secretKeyRef.configDbKey ) | default ( print $url "/config-db" ) }}
  {{- $canaryCheckerDbUrl := ( get $secretData .Values.db.secretKeyRef.canaryCheckerDbKey ) | default ( print $url "/canary-checker" ) }}
  {{- $incidentCommanderDbUrl := ( get $secretData .Values.db.secretKeyRef.incidentCommanderDbKey ) | default ( print $url "/incident-commander" ) }}

  POSTGRES_USER: {{ $user | quote }}
  POSTGRES_PASSWORD: {{ $password | quote }}
  POSTGRES_HOST: {{ $host | quote }}
  {{ .Values.db.secretKeyRef.configDbKey }}: {{ $configDbUrl | quote }}
  {{ .Values.db.secretKeyRef.canaryCheckerDbKey }}: {{ $canaryCheckerDbUrl | quote }}
  {{ .Values.db.secretKeyRef.incidentCommanderDbKey }}: {{ $incidentCommanderDbUrl | quote }}

{{- end }}

---

{{- end }}
