{{- if eq .Values.db.enabled true }}
# PostgreSQL StatefulSet - ConfigMap
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: postgresql-db
        image: postgres:latest
        volumeMounts:
          - name: postgresql-db-disk
            mountPath: /data
        envFrom:
          - secretRef:
              name: {{ .Values.db.secretKeyRef }}
    volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ""
        resources:
          requests:
            storage: 25Gi

---

# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
  metadata:
    name: postgres-db
spec:
  selector:
    app: postgresql-db
  type: LoadBalancer
  ports:
  - port: 5432
  targetPort: 5432

---

{{- if empty .Values.db.secretKeyRef }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-connection
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "postgres-connection") | default dict }}
  {{ $releaseNamespace := .Release.Namespace }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $pgDb := (get $secretData "POSTGRES_DB") | default ("config_db" | b64enc) }}
  POSTGRES_DB: {{ $pgDb | quote }}
  {{- $pgUser := (get $secretData "POSTGRES_USER") | default ("postgres" | b64enc) }}
  POSTGRES_USER: {{ $pgUser | quote }}
  {{- $pgPassword := (get $secretData "POSTGRES_PASSWORD") | default (randAlphaNum 32 | b64enc) }}
  POSTGRES_PASSWORD: {{ $pgPassword | quote }}
  {{- $pgData := (get $secretData "PGDATA") | default ("/data/pgdata" | b64enc) }}
  PGDATA: {{ $pgData | quote }}
  {{- $configDbUrl := (get $secretData "DB_URL_CONFIG_DB") | default ( ( print "postgresql://" $pgUser ":" $pgPassword "@postgres-db." $releaseNamespace ".svc.cluster.local:5432/" $pgDb ) | b64enc ) }}
  DB_URL_CONFIG_DB: {{ $configDbUrl | quote }}
  {{- $incidentCommanderDbUrl := (get $secretData "DB_URL") | default ( ( print "postgresql://" $pgUser ":" $pgPassword "@postgres-db." $releaseNamespace ".svc.cluster.local:5432/" $pgDb ) | b64enc ) }}
  DB_URL_INCIDENT_COMM: {{ $incidentCommanderDbUrl | quote }}
{{- end }}

{{- end }}