apiVersion: v1
kind: Service
metadata:
  name: {{ include "apm-hub.name" . }}
  labels:
    {{- include "apm-hub.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "apm-hub.selectorLabels" . | nindent 4 }}
