apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-db.name" . }}
  labels:
    {{- include "config-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "config-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "config-db.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "config-db.name" . }}-sa
      containers:
        - name: {{ include "config-db.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /app/config-db
          args:
            - serve
            - -vvv
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretKeyRef.name | default "postgres-connection" }}
                  key: {{ .Values.db.secretKeyRef.key | default 'DB_URL' }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.extra }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
