---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-commander
  labels:
    control-plane: incident-commander
spec:
  selector:
    matchLabels:
      control-plane: incident-commander
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: incident-commander
    spec:
      containers:
        - name: incident-commander
          image: docker.io/flanksource/incident-commander:latest
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: incident-commander-postgres-connection-string
                  key: connection-string
          command:
            - /app/incident-commander
          args:
            - serve
            - -vvv
            - --apm-hub=http://apm-hub.apm-hub.svc:8080
            - --canary-checker=http://canary-checker.canary-checker.svc:8080
            - --config-db=http://config-db.config-db.svc:8080
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              memory: 512Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: incident-commander
  name: incident-commander
  namespace: incident-commander
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: incident-commander